# Generated by Django 4.0.5 on 2022-06-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210127_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=2)),
                ('altura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_competicao', models.CharField(blank=None, max_length=200, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_esporte', models.CharField(blank=None, max_length=100, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(blank=None, max_length=50, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='OliGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=None, null=None)),
                ('sede', models.CharField(max_length=200)),
                ('temp', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='event',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='event',
            name='athlete_NOC',
        ),
        migrations.RemoveField(
            model_name='event',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='event',
            name='game',
        ),
        migrations.RemoveField(
            model_name='event',
            name='medal',
        ),
        migrations.AlterModelOptions(
            name='noc',
            options={},
        ),
        migrations.RemoveField(
            model_name='noc',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='noc',
            name='region',
        ),
        migrations.AddField(
            model_name='noc',
            name='notas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='noc',
            name='regiao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='noc',
            name='noc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Medal',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='evento',
            name='atleta_noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.noc'),
        ),
        migrations.AddField(
            model_name='evento',
            name='competicao_nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competicao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atleta'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_medalha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medalha'),
        ),
        migrations.AddField(
            model_name='competicao',
            name='esporte',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='api.esporte'),
        ),
    ]
